version: '3'

services:
    db: 
        image: postgres
        volumes:
              - ./postgres-data:/var/lib/postgresql/data
    web:
        build: .
        command: bash -c "(cd static/semantic/ && gulp build && cd ../../ && python3 manage.py migrate); ((cd static/semantic/ && gulp watch) & python3 manage.py runserver 0.0.0.0:8000)"
        volumes: 
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
