version: '3'

services:
    db: 
        image: postgres
    web:
        build: .
        command: bash -c "(cd static/semantic/ && /usr/bin/gulp build && cd ../../ && python3 manage.py migrate); ((cd static/semantic/ && /usr/bin/gulp watch) & python3 manage.py runserver 0.0.0.0:8000)"
        volumes: 
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
