version: '3'

services:
    db: 
        image: postgres
        volumes:
              - ./postgres-data:/var/lib/postgresql/data
    web:
        build: .
        # Full command for deployment
        command: bash -c "(cd static/semantic/ && gulp build && cd ../../ && python manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstatic --no-input); ((cd static/semantic/ && gulp watch) & gunicorn --bind 0.0.0.0:8000 --reload enceph.wsgi)"

        # Fast command for testing changes quickly that don't affect the CSS or static files
        # command: bash -c "gunicorn --bind 0.0.0.0:8000 --reload enceph.wsgi"
        volumes: 
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            DJANGO_ENV: ${DJANGO_ENV}
            DJANGO_DB: ${DJANGO_DB}
            SECRET_KEY: ${SECRET_KEY}
    nginx:
        image: nginx:1.13
        ports:
            - "${WEB_EXTERNAL_PORT:-9000}:80"
            - "${HTTPS_EXTERNAL_PORT:-443}:443"
        depends_on: 
            - web
        volumes:
            - "${NGINX_CONF_LOCATION:-./config/nginx/conf.d}:/etc/nginx/conf.d"
            - ./certs:/root/certs/
        restart: always
