version: '3'

services:
    db: 
        image: postgres
        volumes:
              - ./postgres-data:/var/lib/postgresql/data
    web:
        build: .
        command: bash -c "(cd static/semantic/ && gulp build && cd ../../ && python3 manage.py migrate && python3 manage.py collectstatic --no-input); ((cd static/semantic/ && gulp watch) & gunicorn --bind 0.0.0.0:8000 --reload enceph.wsgi)"
        volumes: 
            - .:/code
        ports:
            - "${WEB_EXTERNAL_PORT:-8000}:8000"
        depends_on:
            - db
        environment:
            DJANGO_ENV: ${DJANGO_ENV}
            DJANGO_DB: ${DJANGO_DB}
            SECRET_KEY: ${SECRET_KEY}
