# Generated by Django 2.1.4 on 2018-12-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181215_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tool',
        ),
    ]
