# Generated by Django 2.1.4 on 2018-12-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_tool_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='submitter_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
